services:
  web: 
    build:
      context: app
      target: builder
    # flask requires SIGINT to stop gracefully
    # (default stop signal from Compose is SIGTERM)
    stop_signal: SIGINT
    ports:
      - '8000:8000'
    volumes:
      - ./app:/app  # Add volume mapping to ensure code updates are reflected
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development  # Enable development mode for better error messages
